# Generated by Django 3.2.3 on 2022-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='course_id',
        ),
        migrations.AddField(
            model_name='semester',
            name='course_id',
            field=models.ManyToManyField(null=True, related_name='course_id', to='api.Course'),
        ),
    ]
